### ISSUE TITLE
代码下载到本地有一些错误，需确认仓库是否为最新代码

### ISSUE THREAD

**Issue by 0x-wen** [the-web3/blockchain-question#4]
1.bitcoin-sdk-lite 这个前端项目 对前端不熟悉 有调试成功的同学可以更新一下
- 已经使用sudo npm install 安装相关依赖了
![image](https://github.com/the-web3/blockchain-question/assets/51824763/2f9d8a05-8817-40e0-bc64-339d17d8dee8)
2.wallet-chain-node 这个go项目，是很多公链交易签名的合集，采用那个分支到本地是可以运行的
目前是拉取的main分支
![image](https://github.com/the-web3/blockchain-question/assets/51824763/5748f0b3-468e-43f1-9e47-10cb2b2e41f9)

**Comment by leo-shi-dacheng** [comment]
![Uploading WeChat7d2352872c4af5e312e94fece1646ddb.jpg…]()
